# Generated by Django 5.0 on 2024-02-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_kansultatsiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
            ],
        ),
    ]
